version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: clinic-management-mongodb
    ports:
      - "27017:27017" # Expose MongoDB on localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db # Persistent storage

volumes:
  mongodb_data: