name: Build and Test Client and Server

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.22.1
          curl -fsSL "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin/docker-compose
          docker-compose --version

      # Verify Docker is running
      - name: Verify Docker Setup
        run: docker info

      # Adjust system settings for MongoDB
      - name: Adjust System Settings
        run: |
          sudo sysctl -w vm.max_map_count=1677720
          sudo sysctl -w vm.swappiness=1

      # Start Docker Compose for MongoDB
      - name: Start MongoDB with Docker Compose
        run: docker-compose -f clinic-management-server/src/test/resources/docker-compose.yml up -d

      # Set up Java for the server
      - name: Set up JDK 21 for Server
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      # Run Tests
      - name: Run Tests
        working-directory: clinic-management-server
        run: mvn test

      # Tear down Docker Compose
      - name: Tear Down MongoDB
        run: docker-compose -f clinic-management-server/src/test/resources/docker-compose.yml down
