name: Build and Test Client and Server

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Adjust system settings for MongoDB
      - name: Adjust System Settings
        run: |
          sudo sysctl -w vm.max_map_count=1677720
          sudo sysctl -w vm.swappiness=1

      # Start Docker Compose for testing
      - name: Start MongoDB with Docker Compose
        run: docker-compose -f clinic-management-server/src/test/resources/docker-compose.yml up -d

      # Set up Java for the server
      - name: Set up JDK 21 for Server
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      # Run Tests
      - name: Run Tests
        working-directory: clinic-management-server
        run: mvn test

      # Tear down Docker Compose
      - name: Tear Down MongoDB
        run: docker-compose -f clinic-management-server/src/test/resources/docker-compose.yml down
