name: Build and Test Client and Server

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 21 for Server
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      # Install Docker Compose as a CLI plugin
      - name: Install Docker Compose Plugin
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -fsSL "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      # Verify Docker is running
      - name: Verify Docker Setup
        run: docker info

      # Adjust system settings for MongoDB
      - name: Adjust System Settings
        run: |
          sudo sysctl -w vm.max_map_count=1677720
          echo "Skipped adjusting swappiness as it is not supported on this runner."

      # Start Docker Compose for MongoDB
      - name: Start MongoDB with Docker Compose
        run: docker compose -f clinic-management-server/src/test/resources/docker-compose.yml up -d

      # Build and Package Application
      - name: Build and Package Server
        working-directory: clinic-management-server
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml clean package -DskipTests
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      # Run Tests
      - name: Run Tests
        working-directory: clinic-management-server
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml test
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      # Tear down Docker Compose
      - name: Tear Down MongoDB
        run: docker compose -f clinic-management-server/src/test/resources/docker-compose.yml down
